const languageTable =  {
    newOrder:       {english: "New Order"         ,polish: "nowe zamówienie"     ,czech: "nová objednávka",},
    warehouse:      {english: "Warehouse"         ,polish: "magazyn"             ,czech: "Seznam čajů",},
    archive:        {english: "Archive"           ,polish: "archiwum"            ,czech: "Historie objednávek",},
    collapseOrder:  {english: "Collapse Order"    ,polish: "Zwiń zamówienie"     ,czech: "Skryj objednávku",},
    expandOrder:    {english: "Expand Order"      ,polish: "rozwiń zamówienie"   ,czech: "zobraz objednávku",},
    table:          {english: "Table"             ,polish: "stolik"              ,czech: "stůl",},
    discount:       {english: "Discount"          ,polish: "zniżka"              ,czech: "sleva",},
    toGo:           {english: "To Go"             ,polish: "na wagę"             ,czech: "vážené",},
    closeOrder:     {english: "Close order"       ,polish: "zamknij zamóiwnie"   ,czech: "zavřít objednávku",},
    deleteOrder:    {english: "Delete order"      ,polish: "usuń zamówienie"     ,czech: "odstranit objednávku",},
    code:           {english: "Code"              ,polish: "kod"                 ,czech: "kód",},
    name:           {english: "Name"              ,polish: "nazwa"               ,czech: "nazev",},
    type:           {english: "Type"              ,polish: "typ"                 ,czech: "druh",},
    quantity:       {english: "Quantity"          ,polish: "ilość"               ,czech: "množství",},
    price:          {english: "Price"             ,polish: "cena"                ,czech: "cena",},
    hints:          {english: "Hints"             ,polish: "uwagi"               ,czech: "poznámky",},
    discounted:     {english: "Discoutned"        ,polish: "po zniżce"           ,czech: "po slevě",},
    sum:            {english: "Sum"               ,polish: "suma"                ,czech: "celkem",},
    discountedSum:  {english: "Discounted Sum"    ,polish: "suma po zniżce"      ,czech: "celkem po slevě",},
    addPosition:    {english: "Add position"      ,polish: "dodaj pozycję"       ,czech: "přidat položku",},
    save:           {english: "Save"              ,polish: "zapisz"              ,czech: "uložit",},
    delete:         {english: "Delete"            ,polish: "usuń"                ,czech: "odstranit", },
    piece:          {english: "Piece"             ,polish: "sztuka"              ,czech: "kus",},
    teapot:         {english: "Teapot"            ,polish: "czajnik"             ,czech: "konvička",},
    gaiwan:         {english: "Gaiwan"            ,polish: "gaiwan"              ,czech: "gai wan",},
    package:        {english: "Package"           ,polish: "opakowanie"          ,czech: "balení",},
    date:           {english: "Date"              ,polish: "data"                ,czech: "datum",},
    total:          {english: "Total"             ,polish: "suma dnia"           ,czech: "celkem",},
    opened:         {english: "Opened"            ,polish: "otwarto"             ,czech: "otevřený",},
    moreStatistics: {english: "More statistics"   ,polish: "więcej statystyk"    ,czech: "další informace",},
    expandAll:      {english: "Expand all"        ,polish: "rozwiń wszystkie"    ,czech: "zobrazit vše",},
    reopen:         {english: "Reopen"            ,polish: "otwórz ponownie"     ,czech: "otevřít znova ",},
    income:         {english: "Income"            ,polish: "wpływ"               ,czech: "přinos",},
    hour:           {english: "Hour"              ,polish: "godzina"             ,czech: "hodina",},
    menuPositions:  {english: "Menu positions"    ,polish: "pozycje w menu"      ,czech: "číslo položky",},
    backToOrders:   {english: "Back to orders"    ,polish: "wróć do zamówień"    ,czech: "zpět k objednávkám",},
};

module.exports = languageTable;